server:
  port: 8003
spring:
  application:
    name: service_vod
  servlet:
    multipart:
      max-file-size: 1024MB


aliyun:
  vod:
    regionId: cn-shanghai
    accessKeyId: #######
    accessKeySecret: ########