server:
  port: 8003
spring:
  application:
    name: service-vod
  servlet:
    multipart:
      max-file-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


aliyun:
  vod:
    regionId: cn-shanghai
    accessKeyId: #######
    accessKeySecret: ########