server:
  port: 8005
spring:
  application:
    name: service-msm
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
aliyun:
  accessKeyId: ####
  accessKeySecret: ###
  sysDomain: dysmsapi.aliyuncs.com
  sysVersion: 2017-05-25
  sysAction: SendSms
  signName: 在线工单系统
  templateCode: ##